<?php

/**
 * @file
 * Commerce Akeneo i18n module.
 */

/**
 * Implements hook_commerce_akeneo_taxonomy_vocabulary_save().
 */
function commerce_akeneo_i18n_commerce_akeneo_taxonomy_vocabulary_save($vocabulary, $option) {
  $vocabulary->i18n_mode = I18N_MODE_LOCALIZE;
}

/**
 * Implements hook_commerce_akeneo_taxonomy_term_save().
 */
function commerce_akeneo_i18n_commerce_akeneo_taxonomy_term_save($term, $option) {
  // Build context token.
  $context = 'taxonomy:term:' . (int) $term->tid . ':name';

  // Save term translations.
  foreach ($option['labels'] as $locale => $label) {
    // Replace: fr_FR => fr, en_US => en.
    $language = commerce_akeneo_locale_to_language($locale);

    i18n_string_translation_update($context, $label, $language, $term->name);
  }
}
