<?php

/**
 * @file
 * Commerce Akeneo family API file.
 */

/**
 * Allow family name to be overridden.
 *
 * @param string $family_name
 *   family name.
 * @param array  $attribute
 *   Attribute.
 */
function hook_commerce_akeneo_family_get_name_alter(&$family_name, $attribute) {

}

/**
 * Allow family label to be overridden.
 *
 * @param string $family_label
 *   family label.
 * @param array  $attribute
 *   Attribute.
 */
function hook_commerce_akeneo_family_get_label_alter(&$family_label, $attribute) {

}
