<?php

/**
 * @file
 * Commerce Akeneo Title module.
 */

/**
 * Implements hook_commerce_akeneo_family().
 */
function commerce_akeneo_title_commerce_akeneo_family($product_type, $request) {
  // Replace default title property by title field.
  $entity_info = entity_get_info('commerce_product');
  $info        = $entity_info['field replacement']['title'];
  $instance    = field_info_instance('commerce_product', $info['field']['field_name'], $product_type['type']);

  if (empty($instance)) {
    title_field_replacement_toggle('commerce_product', $product_type['type'], 'title');
    title_field_replacement_batch_set('commerce_product', $product_type['type'], 'title');
  }
}
