<?php

/**
 * @file
 * Commerce Akeneo Taxonomy module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_akeneo_taxonomy_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'commerce_akeneo') {
    return "plugins/$plugin_type";
  }
}

/**
 * @param string $code
 * @param string $type (option|category)
 * @param array  $labels
 * @param array  $values
 *
 * @throws \CommerceAkeneoException
 * @throws \Exception
 */
function commerce_akeneo_taxonomy_handle_service($code, $type, $labels, $values) {
  $code = check_plain($code);

  // Store locally details about Akeneo select attribute.
  if (!$taxonomy = commerce_akeneo_taxonomy_load($code, $type)) {
    $taxonomy = array(
      'code' => $code,
      'type' => $type,
    );
  }

  $taxonomy['label'] = commerce_akeneo_get_language($labels);

  commerce_akeneo_taxonomy_save($taxonomy);

  // Create taxonomy vocabulary destination if not already exists.
  if (!$vocabulary = taxonomy_vocabulary_machine_name_load($taxonomy['vocabulary'])) {
    $vocabulary = (object) array(
      'machine_name' => $taxonomy['vocabulary'],
      'description'  => t('Vocabulary created via Akeneo PIM.'),
    );
  }

  $vocabulary->name = $taxonomy['label'];

  // Allow override.
  $context = array(
    'type'   => $type,
    'code'   => $code,
    'labels' => $labels,
    'values' => $values,
  );
  drupal_alter('commerce_akeneo_taxonomy_vocabulary_save', $vocabulary, $context);

  // Write the vocabulary to the database.
  taxonomy_vocabulary_save($vocabulary);

  // Save product to Drupal Queue for future Migrate handle.
  $queue = commerce_akeneo_queue_load($type . ':' . $code, TRUE);

  foreach ($values as $key => $item) {
    $item['machine_name'] = $key;

    if ($item['parent'] == $code) {
      $item['parent'] = NULL;
    }

    if (!$queue->createItem($item)) {
      throw new CommerceAkeneoException('Error while trying to add item to queue.', 500);
    }
  }

  // Reload migrate job list.
  migrate_static_registration();
}

/**
 * Implements hook_commerce_akeneo_taxonomy_vocabulary_save_alter().
 */
function commerce_akeneo_taxonomy_commerce_akeneo_taxonomy_vocabulary_save_alter($vocabulary, $request) {
  $options = isset($request['options']) ? $request['options'] : $request['children'];
  $terms   = array();

  // Create or update terms.
  foreach ($options as $machine_name => $option) {
    $machine_name = taxonomy_machine_name_clean_name($machine_name);

    if (!$term = taxonomy_term_machine_name_load($machine_name, $vocabulary)) {
      $term = (object) array(
        'vid'          => $vocabulary->vid,
        'machine_name' => $machine_name,
        'description'  => '',
        'format'       => 'plain_text',
      );
    }

    $term->name = commerce_akeneo_get_language($option['labels']);

    // Save term and generate tid.
    taxonomy_term_save($term);

    module_invoke_all('commerce_akeneo_taxonomy_term_save', $term, $option);

    // Add temporary parent name.
    $term->parent = !empty($option['parent']) ? $option['parent'] : NULL;

    // Store in local cache the old value to keep parent link.
    $terms[$machine_name] = $term;
  }

  // Support for parent property.
  foreach ($terms as $machine_name => $term) {
    // Skip parent for root category.
    if ($term->parent !== NULL) {
      $parent = taxonomy_machine_name_clean_name($term->parent);

      if (isset($terms[$parent])) {
        $term->parent = $terms[$parent]->tid;

        // Save term and generate tid.
        taxonomy_term_save($term);
      }
    }
  }
}

/**
 * @param string $code
 * @param string $type
 *
 * @return mixed
 */
function commerce_akeneo_taxonomy_load($code, $type = 'option') {
  static $taxonomy = array();

  if (!isset($taxonomy[$type][$code])) {
    $result = db_select('commerce_akeneo_taxonomy', 't')
      ->fields('t')
      ->condition('code', $code)
      ->condition('type', $type)
      ->execute()
      ->fetchAssoc();

    if ($result) {
      return ($taxonomy[$type][$code] = (array) $result);
    }
    else {
      return NULL;
    }
  }

  return $taxonomy[$type][$code];
}

/**
 * @param string $type (option|category)
 *
 * @return array
 */
function commerce_akeneo_taxonomy_load_all($type = 'option') {
  $results = db_select('commerce_akeneo_taxonomy', 't')
    ->fields('t')
    ->condition('type', $type)
    ->execute()
    ->fetchAllAssoc('tid');

  $taxonomies = array();

  foreach ($results as $key => $result) {
    $taxonomies[$key] = (array) $result;
  }

  return $taxonomies;
}

/**
 * @param array $taxonomy
 *
 * @return \DatabaseStatementInterface|int
 * @throws \Exception
 */
function commerce_akeneo_taxonomy_save(&$taxonomy) {
  // Check required arguments.
  if (!isset($taxonomy['code'])) {
    throw new \Exception('Invalid argument');
  }

  // Set default values.
  $taxonomy += array(
    'tid'     => NULL,
    'label'   => $taxonomy['code'],
    'created' => REQUEST_TIME,
    'changed' => REQUEST_TIME,
  );

  if (empty($taxonomy['vocabulary'])) {
    $taxonomy['vocabulary'] = commerce_akeneo_get_machine_name($taxonomy['code'], $taxonomy['type']);
  }

  if (empty($taxonomy['tid'])) {
    unset($taxonomy['tid']);

    $tid = db_insert('commerce_akeneo_taxonomy')
      ->fields(array_keys($taxonomy))
      ->values(array_values($taxonomy))
      ->execute();

    $taxonomy['tid'] = $tid;
  }
  else {
    unset($taxonomy['created']);

    db_update('commerce_akeneo_taxonomy')
      ->condition('tid', $taxonomy['tid'])
      ->fields($taxonomy)
      ->execute();
  }

  return TRUE;
}

/**
 * @param string $code
 */
function commerce_akeneo_taxonomy_delete($code) {
  db_delete('commerce_akeneo_taxonomy')->condition('code', $code)->execute();
}

/**
 * Implements hook_entity_delete().
 */
function commerce_akeneo_taxonomy_entity_delete($entity, $type) {
  if ($type == 'taxonomy_vocabulary') {
    db_delete('commerce_akeneo_taxonomy')->condition('vocabulary', $entity->machine_name)->execute();
  }
}
