<?php

/**
 * @file
 * Commerce Akeneo Field API file.
 */

/**
 * Allow field name to be overridden.
 *
 * @param string $field_name
 *   Field name.
 * @param array  $attribute
 *   Attribute.
 */
function hook_commerce_akeneo_field_get_name_alter(&$field_name, $attribute) {

}

/**
 * Allow field label to be overridden.
 *
 * @param string $field_label
 *   Field label.
 * @param array  $attribute
 *   Attribute.
 */
function hook_commerce_akeneo_field_get_label_alter(&$field_label, $attribute) {

}
