<?php

/**
 * @file
 * Commerce Akeneo Field Group module.
 */

//require_once 'commerce_akeneo_field.api.inc';

// Classes and Interfaces.
//require_once dirname(__FILE__) . '/includes/CommerceAkeneoFieldAbstract.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_akeneo_field_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'commerce_akeneo') {
    return "plugins/$plugin_type";
  }
}
