<?php

/**
 * @file
 * Set up the migration module.
 */

/**
 * Implements hook_disable().
 */
function commerce_akeneo_migrate_disable() {
  MigrateGroup::deregister(COMMERCE_AKENEO_MIGRATE_GROUP_NAME_CATEGORY);
  MigrateGroup::deregister(COMMERCE_AKENEO_MIGRATE_GROUP_NAME_OPTION);
  MigrateGroup::deregister(COMMERCE_AKENEO_MIGRATE_GROUP_NAME_PRODUCT);
  MigrateGroup::deregister(COMMERCE_AKENEO_MIGRATE_GROUP_NAME_PRODUCT_DISPLAY);
}

/**
 * Implements hook_uninstall().
 */
function commerce_akeneo_migrate_uninstall() {
  variable_del('commerce_akeneo_migrate_lease_time');
  variable_del('commerce_akeneo_migrate_product_display_import_group');
  variable_del('commerce_akeneo_migrate_product_display_bundle_auto');
  variable_del('commerce_akeneo_migrate_product_display_bundle');
  variable_del('commerce_akeneo_migrate_product_display_field_auto');
  variable_del('commerce_akeneo_migrate_product_display_field');
}
