<?php

/**
 * @file
 * Commerce Akeneo Migrate module.
 */

const COMMERCE_AKENEO_MIGRATE_DEFAULT_LEASE_TIME = 60;

// Groups for Migrate script.
const COMMERCE_AKENEO_MIGRATE_GROUP_NAME_PRODUCT  = 'commerce_akeneo_product';
const COMMERCE_AKENEO_MIGRATE_GROUP_NAME_CATEGORY = 'commerce_akeneo_category';
const COMMERCE_AKENEO_MIGRATE_GROUP_NAME_OPTION   = 'commerce_akeneo_option';

require_once dirname(__FILE__) . '/commerce_akeneo_migrate.admin.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_akeneo_migrate_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'commerce_akeneo') {
    return "plugins/$plugin_type";
  }
}
